import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import "../styles/globals.css";
import RootLayoutClient from "@/app/_components/RootLayoutClient";

const vazirmatn = Vazirmatn({
  variable: "--font-vazir-matn",
  subsets: ["arabic", "latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "بیمه بازار",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${vazirmatn.variable}`}>
        <RootLayoutClient>{children}</RootLayoutClient>
      </body>
    </html>
  );
}
